application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '86400000'
      refresh-token:
        expiration: '604800000'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   # SQL Server dialect for Azure
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update  # Update schema without dropping existing tables
    show-sql: true
  mail:
    username: mohammadmashhour24@gmail.com
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: fzkq khke mbxe yukj
  application:
    name: GraduationProject
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: 'true'
      max-request-size: 10MB
  datasource:
    password: '#AbuThaher12345'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/hallbooking
  jackson:
    time-zone: UTC  # Added time-zone configuration
  cache:
      type: simple  # Added caching configuration

logging:
  level:
    com:
      example: DEBUG
    root: INFO
server:
  port: ${PORT:8080}
  spring:
    resources:
      cache:
        period: 0
openai:
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
  model:
    name: ft:gpt-3.5-turbo-0125:personal::AiPaoD7j

